services:
  - type: web
    name: yc-scraper-full
    env: python
    buildCommand: |
      pip install -r requirements.txt
      playwright install chromium
    startCommand: "gunicorn index:app"
    plan: free
